name: Generate Datas

on:
  schedule: # execute every 12 hours
    - cron: "* */12 * * *"
  workflow_dispatch:

jobs:
  build:
    name: Jobs to update datas
    runs-on: ubuntu-latest
    steps:
      # Snake Animation
      - uses: Platane/snk@master
        id: snake-gif
        with:
          github_user_name: iarasallesbarbosa
          svg_out_path: dist/github-contribution-grid-snake.svg
          
      - name: Set output to pass data to environment file
        run: echo "MY_DATA=$(<path-to-your-data>)" >> ${{github.workspace}}/myenv
        env:
          PATH_TO_DATA: ${{github.workspace}}/path-to-your-data

      - name: Display the content of the environment file
        run: cat ${{github.workspace}}/myenv

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v3.7.0
        with:
          target_branch: output
          build_dir: dist
          env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            MY_DATA: ${{ env.MY_DATA }}
